Repository CDS-Mobile1/CDS_Server, pull requests merged in 2023-05, with the labels that each got.

#4 #3 [FEAT] 친구, 스토리, 스토리태그 Entity 설계
  Instagram-SERVER/build.gradle
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/friend/domain/Friend.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/member/domain/Member.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/member/repository/MemberRepository.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/post/domain/Post.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/post/domain/PostImage.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/story/domain/Story.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/story/repository/StoryRepository.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/storyTag/domain/StoryTag.java
  Instagram-SERVER/src/test/java/com/sopt/instagram/InstagramSERVER/InstagramServerApplicationTests.java
Labels: 🍑 예슬 🍑, 💫 FEAT 💫

#7 [FEAT]: 특정 멤버 스토리 조회 구현
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/exception/SuccessStatus.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/story/controller/StoryController.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/story/controller/dto/response/StoryInfoDto.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/story/repository/StoryRepository.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/story/service/StoryService.java
Labels: 🍒 지연 🍒, 💫 FEAT 💫

#9 #8 [FEAT] 팔로우한 유저 스토리 목록 조회 API
  .gitignore
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/exception/SuccessStatus.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/friend/controller/FriendController.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/friend/controller/dto/FriendResponseDto.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/friend/repository/FriendRepository.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/friend/service/FriendService.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/friend/service/Impl/FriendServiceImpl.java
Labels: 🍑 예슬 🍑, 💫 FEAT 💫

#13 #6 [FEAT] 스토리에 태그 된 멤버 리스트 조회 API
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/exception/SuccessStatus.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/storyTag/controller/StoryTagController.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/storyTag/controller/dto/response/TaggedMemberInfoDto.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/storyTag/repository/StoryTagRepository.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/storyTag/service/StoryTagService.java
Labels: 🍒 지연 🍒, 💫 FEAT 💫

#16 #15 [FEAT] 게시물 조회 API
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/common/domain/TimeStamped.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/common/dto/ApiResponseDto.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/common/exception/BusinessException.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/common/exception/ControllerExceptionAdvice.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/common/exception/ErrorStatus.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/common/exception/SuccessStatus.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/config/JpaAuditingConfig.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/friend/controller/FriendController.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/friend/domain/Friend.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/friend/service/FriendService.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/friend/service/Impl/FriendServiceImpl.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/member/domain/Member.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/member/service/MemberService.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/post/controller/PostController.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/post/controller/dto/PostResponseDto.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/post/domain/Post.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/post/domain/PostImage.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/post/repository/PostRepository.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/post/service/PostService.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/story/controller/StoryController.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/story/domain/Story.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/storyTag/controller/StoryTagController.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/storyTag/domain/StoryTag.java
Labels: 🍑 예슬 🍑, 💫 FEAT 💫

#18 # 17 [FEAT]: DM조회 API
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/common/exception/SuccessStatus.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/message/controller/MessageController.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/message/controller/dto/MessageResponseDto.java
Labels: 🍒 지연 🍒

#20 #19 [FEAT] 스토리 도메인 관련 수정
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/member/domain/Member.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/story/controller/dto/response/StoryInfoDto.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/story/repository/StoryRepository.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/story/service/StoryService.java
  Instagram-SERVER/src/main/java/com/sopt/instagram/InstagramSERVER/storyTag/controller/dto/response/TaggedMemberInfoDto.java
Labels: 🍒 지연 🍒, 💫 FEAT 💫
